[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[dependencies]
image = "0.25.1"
serde = "1.0.203"
serde_json = "1.0.117"
serialimage = "4.1.1"
wasm-bindgen = "0.2.92"
